---
- name: Create web directories for Keycloak
  loop:
    - "{{ keycloak.prefix.opt }}"
    - "{{ keycloak.prefix.opt }}/conf"
    - "{{ keycloak.prefix.opt }}/themes"
    - "{{ keycloak.prefix.opt }}/providers"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory

- name: Create export directory for Keycloak
  loop:
    - "{{ keycloak.prefix.opt }}/export"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory

- name: Template extra files for Keycloak
  loop:
    - src: keycloak/entrypoint.sh
      dest: "{{ keycloak.prefix.opt }}/entrypoint.sh"
      mode: a+x
  loop_control:
    label: "{{ item.dest }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode|default(omit, true) }}"
  notify: Restart Keycloak
